'use client';
import React, { createContext, useContext, useState } from 'react';

const translations = {
  fr: {
    nav: {
      maison: 'Maison',
      collections: 'Collections',
      catalogue: 'Le Catalogue',
      aPropos: 'À Propos',
      actualites: 'Actualités',
      contact: 'Contact',
      favoris: 'Favoris',
      panier: 'Panier',
      voirPanier: 'Voir mon Panier',
      nosCollections: 'Nos Collections',
      nouvelleEre: 'Nouvelle Ère',
      decouvrir: 'Découvrir',
      experienceAtelier: "L'Expérience Atelier",
      descAtelier: "Chaque pièce est ajustée à vos mesures au sein de notre atelier parisien. Commandez directement en ligne et recevez votre confection sur-mesure.",
      decouvrirBoutique: 'Découvrir la Boutique',
      collection2026: 'Collection 2026',
      menu: 'Menu',
      langue: 'Langue',
    },
    hero: {
      tagline: 'Maison de Haute Couture',
      title: 'Kelly Dress',
      slogan: "L'élégance intemporelle pour le jour le plus précieux.",
      cta: 'Découvrir la Collection',
      explorer: 'Explorer',
    },
    product: {
      maison: 'Maison',
      catalogue: 'Catalogue',
      reference: 'Réf.',
      matieres: 'Matières Nobles',
      nuances: 'Nuances Disponibles',
      silhouette: 'Conseil Silhouette',
      choisissezTaille: 'Choisissez votre taille',
      noteTaille: '*Toutes nos créations finales sont entièrement retravaillées à vos mesures exactes au sein de notre atelier.',
      ajouterPanier: 'Ajouter au Panier',
      selectionnezTaille: 'Sélectionnez une taille',
      demanderDevis: 'Demander un devis',
      favoris: 'Favoris',
      similaires: 'Robes Similaires',
      pourContinuer: 'Pour Continuer',
      devisTitre: 'Devis Personnalisé',
      devisIntro: 'Notre service relation clientèle vous répondra sous 24h avec une estimation personnalisée.',
      devisNom: 'Votre Nom',
      devisEmail: 'Votre Adresse E-mail',
      devisMessage: 'Votre Message / Précisions (Date mariage, modifications éventuelles...)',
      devisPlaceholder: 'Souhaitez-vous personnaliser le décolleté ? Ajuster la longueur de la traîne ? Faites-nous part de vos désirs...',
      devisEnvoyer: 'Envoyer la Demande de Devis',
      devisSucces: 'Demande Envoyée',
      devisMerci: 'Nous vous remercions,',
      devisTransmise: 'Votre demande de devis pour le modèle',
      devisBienTransmise: 'est bien transmise.',
      devisDetail: 'Notre concierge haute couture va étudier votre projet avec le chef d\'atelier et vous recontacter par e-mail dans les plus brefs délais.',
      fermer: 'Fermer la Fenêtre',
    },
    boutiques: {
      title: 'Où Nous Trouver',
      intro: 'Découvrez nos boutiques officielles et nos partenaires agréés à travers l\'Europe.',
      rechercher: 'RECHERCHER UNE VILLE...',
      tousPays: 'Tous les pays',
      france: 'France',
      suisse: 'Suisse',
      italie: 'Italie',
      royaumeUni: 'Royaume-Uni',
      nousContacter: 'Nous Contacter',
      aucunResultat: 'Aucune boutique trouvée pour votre recherche.',
      boutiqueOfficielle: 'Boutique Officielle',
      revendeurAgree: 'Revendeur Agréé',
    },
    contact: {
      title: 'Contact',
      nousEcrire: 'Nous Écrire',
      intro: 'Une question sur un modèle ? Un projet de création sur-mesure ? Nos conseillères sont à votre écoute.',
      maisonParis: 'Maison Kelly Dress Paris',
      coordIntro: 'Notre équipe est à votre disposition pour vous accompagner dans la création de votre robe de mariée de rêve.',
      adresseSalon: 'Adresse du Salon',
      telephone: 'Téléphone',
      relations: 'Relations Clientèle',
      horaires: 'Horaires d\'Ouverture',
      horairesDetail: 'Lundi — Samedi : 10h00 - 19h00',
      horairesNote: '*Uniquement sur rendez-vous privé.',
      envoyerMessage: 'Envoyer un Message',
      nomComplet: 'Votre Nom Complet',
      email: 'Votre Adresse Email',
      telephoneLabel: 'Téléphone',
      dateMariage: 'Date présumée du mariage (Optionnel)',
      message: 'Votre Message',
      placeholderMessage: 'Parlez-nous de vos envies, des silhouettes qui vous inspirent...',
      envoyer: 'Envoyer mon message',
      messageEnvoye: 'Message Envoyé',
      cher: 'Cher(e)',
      messageRecu: 'Nous avons bien reçu votre message et nous vous remercions de l\'intérêt que vous portez à notre Maison.',
      messageReponse: 'Nos conseillères haut couture vont étudier votre demande et vous répondre par e-mail dans les 24 heures ouvrées.',
      nouveauMessage: 'Écrire un nouveau message',
    },
    footer: {
      newsletter: 'La Newsletter',
      newsletterDesc: 'Inscrivez-vous pour recevoir les invitations exclusives à nos défilés, les lancements de collections et l\'actualité de la Maison.',
      newsletterSucces: 'Merci pour votre inscription.',
      emailPlaceholder: 'VOTRE ADRESSE EMAIL',
      sinscrire: 'S\'inscrire',
      navigation: 'Navigation',
      maisonParis: 'Maison',
      email: 'support@kellydress.co',
      telephone: '06 26 75 13 11',
      horaires: 'Sur rendez-vous uniquement.\nLundi — Samedi : 10h00 - 19h00',
      instagram: '@kellydress_paris',
      instagramTitle: 'Instagram',
      droits: 'Tous droits réservés.',
      mentions: 'Mentions Légales',
      cgu: 'CGU',
      confidentialite: 'Politique de Confidentialité',
    },
    cart: {
      monPanier: 'Mon Panier',
      fermer: 'Fermer',
      taille: 'Taille',
      sousTotal: 'Sous-total',
      livraison: 'Livraison premium offerte en France et en Europe. Confection sur mesure incluse.',
      payer: 'Procéder au paiement',
      vide: 'Votre panier est vide',
      videDesc: 'Découvrez notre collection de robes de mariée d\'exception pour commencer vos achats.',
      continuer: 'Continuer la visite',
      paiement: 'Paiement Sécurisé',
      paiementDesc: 'Veuillez renseigner vos informations de livraison haute couture.',
      nom: 'Nom Complet',
      email: 'Adresse Email',
      adresse: 'Adresse de Livraison',
      codePostal: 'Code Postal',
      ville: 'Ville',
      carte: 'Numéro de Carte Bancaire',
      cartePlaceholder: '4000 1234 5678 9010',
      total: 'Total final à payer :',
      confirmer: 'Confirmer la commande',
      retour: 'Retour',
      merci: 'Merci pour votre commande',
      cher: 'Chère',
      commandeValidee: 'votre commande a été validée avec succès.',
      emailConfirmation: 'Un e-mail de confirmation détaillant la facture et le suivi de livraison a été envoyé à',
      atelier: 'Nos ateliers de couture à Paris vont débuter la confection sur-mesure de votre robe sous 48h. Nous vous contacterons par téléphone pour valider vos mesures exactes.',
      supprimer: 'Supprimer',
    },
    booking: {
      fermer: 'Fermer',
      rendezVous: 'Rendez-vous Privé',
      reserver: 'Réserver une Séance d\'Essayage',
      intro: 'Nous serions honorés de vous accueillir au sein de nos salons privés pour vous guider dans la recherche de votre robe d\'exception.',
      nom: 'Nom Complet',
      email: 'Adresse Email',
      telephone: 'Numéro de Téléphone',
      boutique: 'Boutique',
      paris: 'Paris — Faubourg Saint-Honoré',
      lyon: 'Lyon — Place Bellecour',
      geneve: 'Genève — Rue du Rhône',
      date: 'Date souhaitée',
      heure: 'Heure souhaitée',
      demandes: 'Demandes Particulières / Silhouette recherchée',
      confirmer: 'Confirmer la demande',
      succes: 'Votre demande est enregistrée',
      merci: 'Chère',
      remerciement: 'nous vous remercions de l\'intérêt porté à Kelly Dress.',
      conseillere: 'Une conseillère haute couture va vous contacter dans les 24 heures pour finaliser votre rendez-vous privé.',
      recapitulatif: 'Récapitulatif de votre demande',
      fermerFenetre: 'Fermer la fenêtre',
    },
    blog: {
      retour: 'Retour aux actualités',
      title: 'Actualités',
      intro: 'Découvrez les coulisses de la Maison Kelly Dress, les inspirations de nos collections et les conseils de nos artisans d\'art.',
      lireAussi: 'Lire aussi',
    },
    about: {
      title: 'La Maison',
      subtitle: 'La Maison',
      hero: 'L\'Art de la Haute Couture Parisienne',
      heroDesc: 'Depuis notre atelier parisien, la Maison Kelly Dress perpétue l\'excellence de la couture française en imaginant des robes de mariée d\'exception.',
      p1: 'Depuis nos débuts dans l\'intimité d\'un atelier parisien, la Maison Kelly Dress imagine des créations d\'exception pour les mariées en quête de raffinement et de haute couture.',
      p2: 'Chaque silhouette est une œuvre d\'art façonnée à la main par nos artisans d\'art. Des dentelles de Calais historiques aux soies sauvages de Côme, chaque matière est rigoureusement sélectionnée pour son tombé parfait, son drapé sculptural et sa sensorialité.',
      p3: 'Notre esthétique marie un minimalisme contemporain à la grandeur des silhouettes classiques, créant un équilibre parfait entre modernité audacieuse et grâce intemporelle.',
      decouvrir: 'Découvrir Notre Atelier',
      heritage: 'Notre Héritage',
      heritageDesc: 'Née d\'une vision audacieuse mêlant tradition et modernité, la Maison Kelly Dress incarne l\'élégance intemporelle depuis sa création. Chaque robe est le fruit d\'un dialogue entre le geste artisanal le plus pur et une sensibilité contemporaine.',
      metiers: 'Nos Métiers d\'Art',
      metiersDesc: 'Dans notre atelier du 8ème arrondissement parisien, une équipe de couturières, modeleurs et brodeurs d\'art donne vie à vos rêves. Dentelles de Calais, soies sauvages de Côme, perles de rocaille — chaque matière est manipulée avec le respect qu\'elle mérite.',
      engagement: 'Notre Engagement',
      engagementDesc: 'Nous croyons en une mode lente, responsable et profondément humaine. Chaque création Kelly Dress est confectionnée sur mesure dans un souci d\'excellence et de durabilité. Robes héritage destinées à traverser les générations.',
    },
    catalog: {
      title: 'Catalogue',
      toutes: 'Toutes les Robes',
      filtrer: 'Filtrer',
      reinitialiser: 'Réinitialiser',
      filtreCollection: 'Collection',
      filtreSilhouette: 'Silhouette',
      filtreStyle: 'Style',
      filtreMatiere: 'Matière',
      filtreCouleur: 'Couleur',
      filtrePrix: 'Budget',
      filtreTaille: 'Taille',
      modele: 'modèle',
      modeles: 'modèles',
      toutEffacer: 'Tout effacer',
      aucunResultat: 'Aucun modèle trouvé',
      aucunResultatDesc: 'Essayez de modifier vos filtres ou votre recherche pour trouver la robe de vos rêves.',
      voirModeles: 'Voir',
      rechercher: 'Rechercher une robe...',
      reinitialiser: 'Réinitialiser',
      nothing: 'Aucune robe trouvée pour cette collection.',
      modele: 'modèle',
      modeles: 'modèles',
      filtreCollection: 'Collection',
      filtreSilhouette: 'Silhouette',
      filtreStyle: 'Style',
      filtrePrix: 'Prix',
      filtreTaille: 'Taille (Essayage)',
    },
    wishlist: {
      title: 'Mes Favoris',
      empty: 'Votre liste de favoris est vide.',
      emptyDesc: 'Parcourez notre collection et ajoutez vos robes préférées à vos favoris pour les retrouver facilement.',
      decouvrir: 'Découvrir le Catalogue',
      retirer: 'Retirer des favoris',
      reference: 'Réf.',
    },
    featured: {
      subtitle: 'Nos Créations',
      title: 'Robes en Vedette',
      voir: 'Voir la Robe',
      voirTout: 'Voir Toutes les Robes',
    },
    general: {
      et: 'et',
      charger: 'Charger...',
      erreur: 'Une erreur est survenue.',
    },
  },
  en: {
    nav: {
      maison: 'Home',
      collections: 'Collections',
      catalogue: 'Catalog',
      aPropos: 'About',
      actualites: 'News',
      contact: 'Contact',
      favoris: 'Wishlist',
      panier: 'Cart',
      voirPanier: 'View my Cart',
      nosCollections: 'Our Collections',
      nouvelleEre: 'New Era',
      decouvrir: 'Discover',
      experienceAtelier: 'The Atelier Experience',
      descAtelier: 'Each piece is tailored to your measurements in our Parisian workshop. Order directly online and receive your made-to-measure creation.',
      decouvrirBoutique: 'Discover the Boutique',
      collection2026: '2026 Collection',
      menu: 'Menu',
      langue: 'Language',
    },
    hero: {
      tagline: 'Haute Couture Maison',
      title: 'Kelly Dress',
      slogan: 'Timeless elegance for the most precious day.',
      cta: 'Discover the Collection',
      explorer: 'Explore',
    },
    product: {
      maison: 'Home',
      catalogue: 'Catalog',
      reference: 'Ref.',
      matieres: 'Fine Materials',
      nuances: 'Available Shades',
      silhouette: 'Silhouette Advice',
      choisissezTaille: 'Choose your size',
      noteTaille: '*All final creations are entirely reworked to your exact measurements in our workshop.',
      ajouterPanier: 'Add to Cart',
      selectionnezTaille: 'Select a size',
      demanderDevis: 'Request a quote',
      favoris: 'Wishlist',
      similaires: 'Similar Dresses',
      pourContinuer: 'To Continue',
      devisTitre: 'Custom Quote',
      devisIntro: 'Our customer service will respond within 24 hours with a personalized estimate.',
      devisNom: 'Your Full Name',
      devisEmail: 'Your Email Address',
      devisMessage: 'Your Message / Details (Wedding date, modifications...)',
      devisPlaceholder: 'Would you like to customize the neckline? Adjust the train length? Share your wishes with us...',
      devisEnvoyer: 'Send Quote Request',
      devisSucces: 'Request Sent',
      devisMerci: 'Thank you,',
      devisTransmise: 'Your quote request for the model',
      devisBienTransmise: 'has been successfully transmitted.',
      devisDetail: 'Our haute couture concierge will study your project with the workshop director and contact you by email as soon as possible.',
      fermer: 'Close Window',
    },
    boutiques: {
      title: 'Find Us',
      intro: 'Discover our official boutiques and approved partners across Europe.',
      rechercher: 'SEARCH A CITY...',
      tousPays: 'All countries',
      france: 'France',
      suisse: 'Switzerland',
      italie: 'Italy',
      royaumeUni: 'United Kingdom',
      nousContacter: 'Contact Us',
      aucunResultat: 'No boutiques found for your search.',
      boutiqueOfficielle: 'Official Boutique',
      revendeurAgree: 'Approved Retailer',
    },
    contact: {
      title: 'Contact',
      nousEcrire: 'Write to Us',
      intro: 'A question about a model? A custom creation project? Our advisors are here to listen.',
      maisonParis: 'Kelly Dress Paris Maison',
      coordIntro: 'Our team is here to guide you in finding your exceptional wedding dress.',
      adresseSalon: 'Salon Address',
      telephone: 'Phone',
      relations: 'Client Relations',
      horaires: 'Opening Hours',
      horairesDetail: 'Monday — Saturday: 10:00 AM - 7:00 PM',
      horairesNote: '*By private appointment only.',
      envoyerMessage: 'Send a Message',
      nomComplet: 'Your Full Name',
      email: 'Your Email Address',
      telephoneLabel: 'Phone',
      dateMariage: 'Estimated wedding date (Optional)',
      message: 'Your Message',
      placeholderMessage: 'Tell us about your wishes, the silhouettes that inspire you...',
      envoyer: 'Send my message',
      messageEnvoye: 'Message Sent',
      cher: 'Dear',
      messageRecu: 'We have received your message and thank you for your interest in our Maison.',
      messageReponse: 'Our haute couture advisors will review your request and respond by email within 24 business hours.',
      nouveauMessage: 'Write a new message',
    },
    footer: {
      newsletter: 'Newsletter',
      newsletterDesc: 'Subscribe to receive exclusive invitations to our fashion shows, collection launches, and Maison news.',
      newsletterSucces: 'Thank you for subscribing.',
      emailPlaceholder: 'YOUR EMAIL ADDRESS',
      sinscrire: 'Subscribe',
      navigation: 'Navigation',
      maisonParis: 'Maison',
      email: 'support@kellydress.co',
      telephone: '06 26 75 13 11',
      horaires: 'By appointment only.\nMonday — Saturday: 10:00 AM - 7:00 PM',
      instagram: '@kellydress_paris',
      instagramTitle: 'Instagram',
      droits: 'All rights reserved.',
      mentions: 'Legal Notice',
      cgu: 'TOS',
      confidentialite: 'Privacy Policy',
    },
    cart: {
      monPanier: 'My Cart',
      fermer: 'Close',
      taille: 'Size',
      sousTotal: 'Subtotal',
      livraison: 'Free premium delivery in France and Europe. Made-to-measure included.',
      payer: 'Proceed to Checkout',
      vide: 'Your cart is empty',
      videDesc: 'Discover our collection of exceptional wedding dresses to start shopping.',
      continuer: 'Continue Browsing',
      paiement: 'Secure Payment',
      paiementDesc: 'Please fill in your haute couture delivery information.',
      nom: 'Full Name',
      email: 'Email Address',
      adresse: 'Delivery Address',
      codePostal: 'Postal Code',
      ville: 'City',
      carte: 'Credit Card Number',
      cartePlaceholder: '4000 1234 5678 9010',
      total: 'Total to pay:',
      confirmer: 'Confirm Order',
      retour: 'Back',
      merci: 'Thank you for your order',
      cher: 'Dear',
      commandeValidee: 'your order has been successfully confirmed.',
      emailConfirmation: 'A confirmation email detailing the invoice and delivery tracking has been sent to',
      atelier: 'Our Parisian couture workshops will begin making your made-to-measure dress within 48 hours. We will contact you by phone to confirm your exact measurements.',
      supprimer: 'Remove',
    },
    booking: {
      fermer: 'Close',
      rendezVous: 'Private Appointment',
      reserver: 'Book a Fitting Session',
      intro: 'We would be honored to welcome you to our private salons to guide you in finding your exceptional dress.',
      nom: 'Full Name',
      email: 'Email Address',
      telephone: 'Phone Number',
      boutique: 'Boutique',
      paris: 'Paris — Faubourg Saint-Honoré',
      lyon: 'Lyon — Place Bellecour',
      geneve: 'Geneva — Rue du Rhône',
      date: 'Preferred Date',
      heure: 'Preferred Time',
      demandes: 'Special Requests / Silhouette you are looking for',
      confirmer: 'Confirm Request',
      succes: 'Your request has been registered',
      merci: 'Dear',
      remerciement: 'thank you for your interest in Kelly Dress.',
      conseillere: 'A haute couture advisor will contact you within 24 hours to finalize your private appointment.',
      recapitulatif: 'Summary of your request',
      fermerFenetre: 'Close Window',
    },
    blog: {
      retour: 'Back to News',
      title: 'News',
      intro: 'Discover behind the scenes of Maison Kelly Dress, inspirations for our collections, and advice from our master artisans.',
      lireAussi: 'Read also',
    },
    about: {
      title: 'The Maison',
      subtitle: 'The Maison',
      hero: 'The Art of Parisian Haute Couture',
      heroDesc: 'From our Parisian workshop, Maison Kelly Dress perpetuates the excellence of French couture by creating exceptional wedding dresses.',
      p1: 'Since our beginnings in the intimacy of a Parisian workshop, Maison Kelly Dress has been creating exceptional designs for brides seeking refinement and haute couture.',
      p2: 'Each silhouette is a work of art handcrafted by our artisans. From historic Calais lace to wild Como silks, every material is rigorously selected for its perfect drape, sculptural flow, and sensoriality.',
      p3: 'Our aesthetic marries contemporary minimalism with the grandeur of classic silhouettes, creating a perfect balance between bold modernity and timeless grace.',
      decouvrir: 'Discover Our Workshop',
      heritage: 'Our Heritage',
      heritageDesc: 'Born from a bold vision blending tradition and modernity, Maison Kelly Dress embodies timeless elegance since its creation. Each dress is the result of a dialogue between the purest artisanal gesture and a contemporary sensibility.',
      metiers: 'Our Crafts',
      metiersDesc: 'In our workshop in Paris\'s 8th arrondissement, a team of seamstresses, pattern makers, and embroidery artists bring your dreams to life. Calais lace, wild Como silks, glass beads — each material is handled with the respect it deserves.',
      engagement: 'Our Commitment',
      engagementDesc: 'We believe in slow, responsible, and deeply humane fashion. Each Kelly Dress creation is made to measure with a commitment to excellence and sustainability. Heritage dresses meant to last for generations.',
    },
    catalog: {
      title: 'Catalog',
      toutes: 'All Dresses',
      filtrer: 'Filter',
      reinitialiser: 'Reset',
      filtreCollection: 'Collection',
      filtreSilhouette: 'Silhouette',
      filtreStyle: 'Style',
      filtreMatiere: 'Material',
      filtreCouleur: 'Color',
      filtrePrix: 'Budget',
      filtreTaille: 'Size',
      modele: 'model',
      modeles: 'models',
      toutEffacer: 'Clear all',
      aucunResultat: 'No models found',
      aucunResultatDesc: 'Try adjusting your filters or search to find the dress of your dreams.',
      voirModeles: 'View',
      rechercher: 'Search for a dress...',
      reinitialiser: 'Reset',
      nothing: 'No dresses found for this collection.',
      modele: 'dress',
      modeles: 'dresses',
      filtreCollection: 'Collection',
      filtreSilhouette: 'Silhouette',
      filtreStyle: 'Style',
      filtrePrix: 'Price',
      filtreTaille: 'Size (Fitting)',
    },
    wishlist: {
      title: 'My Wishlist',
      empty: 'Your wishlist is empty.',
      emptyDesc: 'Browse our collection and add your favorite dresses to your wishlist to find them easily.',
      decouvrir: 'Discover the Catalog',
      retirer: 'Remove from wishlist',
      reference: 'Ref.',
    },
    featured: {
      subtitle: 'Our Creations',
      title: 'Featured Dresses',
      voir: 'View the Dress',
      voirTout: 'View All Dresses',
    },
    general: {
      et: 'and',
      charger: 'Loading...',
      erreur: 'An error occurred.',
    },
  },
  es: {
    nav: {
      maison: 'Inicio',
      collections: 'Colecciones',
      catalogue: 'Catálogo',
      aPropos: 'Sobre Nosotros',
      actualites: 'Noticias',
      contact: 'Contacto',
      favoris: 'Favoritos',
      panier: 'Carrito',
      voirPanier: 'Ver mi Carrito',
      nosCollections: 'Nuestras Colecciones',
      nouvelleEre: 'Nueva Era',
      decouvrir: 'Descubrir',
      experienceAtelier: 'La Experiencia del Atelier',
      descAtelier: 'Cada pieza se ajusta a sus medidas en nuestro taller parisino. Ordene directamente en línea y reciba su creación a medida.',
      decouvrirBoutique: 'Descubrir la Boutique',
      collection2026: 'Colección 2026',
      menu: 'Menú',
      langue: 'Idioma',
    },
    hero: {
      tagline: 'Casa de Alta Costura',
      title: 'Kelly Dress',
      slogan: 'Elegancia atemporal para el día más preciado.',
      cta: 'Descubrir la Colección',
      explorer: 'Explorar',
    },
    product: {
      maison: 'Inicio',
      catalogue: 'Catálogo',
      reference: 'Ref.',
      matieres: 'Materiales Nobles',
      nuances: 'Tonos Disponibles',
      silhouette: 'Consejo de Silueta',
      choisissezTaille: 'Elija su talla',
      noteTaille: '*Todas las creaciones finales se rehacen completamente a sus medidas exactas en nuestro taller.',
      ajouterPanier: 'Añadir al Carrito',
      selectionnezTaille: 'Seleccione una talla',
      demanderDevis: 'Solicitar presupuesto',
      favoris: 'Favoritos',
      similaires: 'Vestidos Similares',
      pourContinuer: 'Para Continuar',
      devisTitre: 'Presupuesto Personalizado',
      devisIntro: 'Nuestro servicio de atención al cliente le responderá en 24 horas con un presupuesto personalizado.',
      devisNom: 'Su Nombre Completo',
      devisEmail: 'Su Correo Electrónico',
      devisMessage: 'Su Mensaje / Detalles (Fecha de boda, modificaciones...)',
      devisPlaceholder: '¿Desea personalizar el escote? ¿Ajustar la longitud de la cola? Comparta sus deseos con nosotros...',
      devisEnvoyer: 'Enviar Solicitud de Presupuesto',
      devisSucces: 'Solicitud Enviada',
      devisMerci: 'Gracias,',
      devisTransmise: 'Su solicitud de presupuesto para el modelo',
      devisBienTransmise: 'ha sido transmitida correctamente.',
      devisDetail: 'Nuestra conserje de alta costura estudiará su proyecto con el jefe de taller y le contactará por correo electrónico lo antes posible.',
      fermer: 'Cerrar Ventana',
    },
    boutiques: {
      title: 'Encuéntranos',
      intro: 'Descubra nuestras boutiques oficiales y socios autorizados en toda Europa.',
      rechercher: 'BUSCAR UNA CIUDAD...',
      tousPays: 'Todos los países',
      france: 'Francia',
      suisse: 'Suiza',
      italie: 'Italia',
      royaumeUni: 'Reino Unido',
      nousContacter: 'Contáctenos',
      aucunResultat: 'No se encontraron boutiques para su búsqueda.',
      boutiqueOfficielle: 'Boutique Oficial',
      revendeurAgree: 'Distribuidor Autorizado',
    },
    contact: {
      title: 'Contacto',
      nousEcrire: 'Escríbanos',
      intro: '¿Una pregunta sobre un modelo? ¿Un proyecto de creación a medida? Nuestras asesoras están a su disposición.',
      maisonParis: 'Maison Kelly Dress París',
      coordIntro: 'Nuestro equipo está a su disposición para guiarle en la búsqueda de su vestido de novia excepcional.',
      adresseSalon: 'Dirección del Salón',
      telephone: 'Teléfono',
      relations: 'Relaciones con Clientes',
      horaires: 'Horario de Apertura',
      horairesDetail: 'Lunes — Sábado: 10:00 - 19:00',
      horairesNote: '*Solo con cita privada.',
      envoyerMessage: 'Enviar un Mensaje',
      nomComplet: 'Su Nombre Completo',
      email: 'Su Correo Electrónico',
      telephoneLabel: 'Teléfono',
      dateMariage: 'Fecha estimada de boda (Opcional)',
      message: 'Su Mensaje',
      placeholderMessage: 'Háblenos de sus deseos, de las siluetas que le inspiran...',
      envoyer: 'Enviar mi mensaje',
      messageEnvoye: 'Mensaje Enviado',
      cher: 'Querido(a)',
      messageRecu: 'Hemos recibido su mensaje y le agradecemos su interés en nuestra Maison.',
      messageReponse: 'Nuestras asesoras de alta costura estudiarán su solicitud y le responderán por correo electrónico en un plazo de 24 horas hábiles.',
      nouveauMessage: 'Escribir un nuevo mensaje',
    },
    footer: {
      newsletter: 'Boletín',
      newsletterDesc: 'Suscríbase para recibir invitaciones exclusivas a nuestros desfiles, lanzamientos de colecciones y noticias de la Maison.',
      newsletterSucces: 'Gracias por suscribirse.',
      emailPlaceholder: 'SU CORREO ELECTRÓNICO',
      sinscrire: 'Suscribirse',
      navigation: 'Navegación',
      maisonParis: 'Maison',
      email: 'support@kellydress.co',
      telephone: '06 26 75 13 11',
      horaires: 'Solo con cita.\nLunes — Sábado: 10:00 - 19:00',
      instagram: '@kellydress_paris',
      instagramTitle: 'Instagram',
      droits: 'Todos los derechos reservados.',
      mentions: 'Aviso Legal',
      cgu: 'Términos',
      confidentialite: 'Política de Privacidad',
    },
    cart: {
      monPanier: 'Mi Carrito',
      fermer: 'Cerrar',
      taille: 'Talla',
      sousTotal: 'Subtotal',
      livraison: 'Entrega premium gratuita en Francia y Europa. Confección a medida incluida.',
      payer: 'Proceder al Pago',
      vide: 'Su carrito está vacío',
      videDesc: 'Descubra nuestra colección de vestidos de novia excepcionales para empezar a comprar.',
      continuer: 'Seguir Navegando',
      paiement: 'Pago Seguro',
      paiementDesc: 'Por favor, complete su información de entrega de alta costura.',
      nom: 'Nombre Completo',
      email: 'Correo Electrónico',
      adresse: 'Dirección de Entrega',
      codePostal: 'Código Postal',
      ville: 'Ciudad',
      carte: 'Número de Tarjeta',
      cartePlaceholder: '4000 1234 5678 9010',
      total: 'Total a pagar:',
      confirmer: 'Confirmar Pedido',
      retour: 'Volver',
      merci: 'Gracias por su pedido',
      cher: 'Estimado(a)',
      commandeValidee: 'su pedido ha sido confirmado con éxito.',
      emailConfirmation: 'Se ha enviado un correo de confirmación con la factura y el seguimiento de la entrega a',
      atelier: 'Nuestros talleres de costura en París comenzarán la confección a medida de su vestido en 48 horas. Le contactaremos por teléfono para confirmar sus medidas exactas.',
      supprimer: 'Eliminar',
    },
    booking: {
      fermer: 'Cerrar',
      rendezVous: 'Cita Privada',
      reserver: 'Reservar una Sesión de Prueba',
      intro: 'Nos sentiríamos honrados de recibirle en nuestros salones privados para guiarle en la búsqueda de su vestido excepcional.',
      nom: 'Nombre Completo',
      email: 'Correo Electrónico',
      telephone: 'Número de Teléfono',
      boutique: 'Boutique',
      paris: 'París — Faubourg Saint-Honoré',
      lyon: 'Lyon — Place Bellecour',
      geneve: 'Ginebra — Rue du Rhône',
      date: 'Fecha deseada',
      heure: 'Hora deseada',
      demandes: 'Solicitudes Especiales / Silueta buscada',
      confirmer: 'Confirmar Solicitud',
      succes: 'Su solicitud ha sido registrada',
      merci: 'Estimado(a)',
      remerciement: 'gracias por su interés en Kelly Dress.',
      conseillere: 'Una asesora de alta costura le contactará en 24 horas para finalizar su cita privada.',
      recapitulatif: 'Resumen de su solicitud',
      fermerFenetre: 'Cerrar Ventana',
    },
    blog: {
      retour: 'Volver a Noticias',
      title: 'Noticias',
      intro: 'Descubra el detrás de escena de Maison Kelly Dress, las inspiraciones de nuestras colecciones y los consejos de nuestros artesanos.',
      lireAussi: 'Leer también',
    },
    about: {
      title: 'La Maison',
      subtitle: 'La Maison',
      hero: 'El Arte de la Alta Costura Parisina',
      heroDesc: 'Desde nuestro taller parisino, Maison Kelly Dress perpetúa la excelencia de la costura francesa creando vestidos de novia excepcionales.',
      p1: 'Desde nuestros inicios en la intimidad de un taller parisino, Maison Kelly Dress crea diseños excepcionales para novias que buscan refinamiento y alta costura.',
      p2: 'Cada silueta es una obra de arte hecha a mano por nuestros artesanos. Desde los encajes históricos de Calais hasta las sedas salvajes de Como, cada material es rigurosamente seleccionado por su caída perfecta, drapeado escultural y sensorialidad.',
      p3: 'Nuestra estética combina el minimalismo contemporáneo con la grandeza de las siluetas clásicas, creando un equilibrio perfecto entre modernidad audaz y gracia atemporal.',
      decouvrir: 'Descubrir Nuestro Taller',
      heritage: 'Nuestro Legado',
      heritageDesc: 'Nacida de una visión audaz que combina tradición y modernidad, Maison Kelly Dress encarna la elegancia atemporal desde su creación. Cada vestido es el fruto de un diálogo entre el gesto artesanal más puro y una sensibilidad contemporánea.',
      metiers: 'Nuestros Oficios',
      metiersDesc: 'En nuestro taller del distrito 8 de París, un equipo de costureras, modelistas y bordadores da vida a sus sueños. Encajes de Calais, sedas salvajes de Como, cuentas de vidrio — cada material se maneja con el respeto que merece.',
      engagement: 'Nuestro Compromiso',
      engagementDesc: 'Creemos en una moda lenta, responsable y profundamente humana. Cada creación de Kelly Dress se confecciona a medida con un compromiso de excelencia y sostenibilidad. Vestidos heredados destinados a perdurar generaciones.',
    },
    catalog: {
      title: 'Catálogo',
      toutes: 'Todos los Vestidos',
      filtrer: 'Filtrar',
      reinitialiser: 'Reiniciar',
      filtreCollection: 'Colección',
      filtreSilhouette: 'Silueta',
      filtreStyle: 'Estilo',
      filtreMatiere: 'Material',
      filtreCouleur: 'Color',
      filtrePrix: 'Presupuesto',
      filtreTaille: 'Talla',
      modele: 'modelo',
      modeles: 'modelos',
      toutEffacer: 'Borrar todo',
      aucunResultat: 'No se encontraron modelos',
      aucunResultatDesc: 'Intenta modificar tus filtros o búsqueda para encontrar el vestido de tus sueños.',
      voirModeles: 'Ver',
      rechercher: 'Buscar un vestido...',
      reinitialiser: 'Restablecer',
      nothing: 'No se encontraron vestidos para esta colección.',
      modele: 'vestido',
      modeles: 'vestidos',
      filtreCollection: 'Colección',
      filtreSilhouette: 'Silueta',
      filtreStyle: 'Estilo',
      filtrePrix: 'Precio',
      filtreTaille: 'Talla (Prueba)',
    },
    wishlist: {
      title: 'Mis Favoritos',
      empty: 'Su lista de favoritos está vacía.',
      emptyDesc: 'Explore nuestra colección y añada sus vestidos favoritos para encontrarlos fácilmente.',
      decouvrir: 'Descubrir el Catálogo',
      retirer: 'Eliminar de favoritos',
      reference: 'Ref.',
    },
    featured: {
      subtitle: 'Nuestras Creaciones',
      title: 'Vestidos Destacados',
      voir: 'Ver el Vestido',
      voirTout: 'Ver Todos los Vestidos',
    },
    general: {
      et: 'y',
      charger: 'Cargando...',
      erreur: 'Ocurrió un error.',
    },
  },
};

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

export const useTranslation = () => {
  const { lang } = useContext(LanguageContext);
  const t = (key) => {
    const keys = key.split('.');
    let value = translations[lang];
    for (const k of keys) {
      value = value?.[k];
    }
    return value || key;
  };
  return { t, lang };
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    if (typeof window !== 'undefined') {
      return localStorage.getItem('kelly-lang') || 'fr';
    }
    return 'fr';
  });

  const handleSetLang = (newLang) => {
    setLang(newLang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('kelly-lang', newLang);
    }
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang: handleSetLang, translations }}>
      {children}
    </LanguageContext.Provider>
  );
};
